### ISSUE TITLE
slow merging

### ISSUE THREAD

**Issue by justin-f-perez** [justin-f-perez/ParallelSort#13]
PLEASE ASSIGN TO YOURSELF IF YOU'RE GOING TO HANDLE THIS, otherwise I'll assign it to myself tomorrow

according flame graph from profiling, merging is the biggest bottleneck right now. I'm guessing it's the overhead of the "PriorityQueue as a min-heap". I thought this would reduce the total number of comparisons required, but I think the overhead of constructing a PriorityQueue and popping buffers in and out of it dwarfs any gains. That explains why run time always scales with the number of threads on my machine (because we're doing a K-way merge where K=t=# of threads)

**Comment by mir-rahsin-mulk** [comment]
I'm working on making the merge parallel and use all cores, which is not how it is currently implemented. Unless I am misunderstanding the code.
